version: "3.8"

name: test-samuel

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:delegated
      - ./tools/docker/web/config.conf:/etc/nginx/conf.d/default.conf
    links:
      - php


  php:
    restart: unless-stopped
    image: lucasluk798/php:8.2
    
    volumes:
      - .:/var/www:delegated
    environment:
      - APP_ENV=dev

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

  database:
      image: 'mysql:8.0'
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todo-Symfony
      ports:
          - '3306'
      volumes:
          - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "3080:80"
    environment:
      - PMA_ARBITRARY=1

  # encore:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-Node
  #   volumes:
  #     - .:/var/www
  #   working_dir: /var/www
  #   ports:
  #     - "8080:8080"
  #   command: "npm run dev-server"

  # encore:
  #   image: node:latest
  #   volumes:
  #       - .:/var/www
  #   working_dir: /var/www
  #   command: >
  #       sh -c "apt update &&
  #               npm install &&
  #               npm run dev -- --port 8080"
  #   expose:
  #     - "8080"
  #   ports:
  #       - "8080:8080"
  #   environment:
  #     - SERVER_PORT=8080

volumes:
  db_data: {}

networks:
  dev:
